#!/bin/sh

export UAVCAN__UDP__IP__STRING=127.42.0.0
export UAVCAN__NODE__ID__NATURAL16=88
export UAVCAN__DIAGNOSTIC__VERBOSITY__NATURAL8=1
export UAVCAN__PUB__IO_STATUS__ID__NATURAL16=1
export UAVCAN__PUB__CAPTURE__ID__NATURAL16=2
export UAVCAN__SUB__IO_CONFIG__ID__NATURAL16=3
export UAVCAN__SUB__SPOOF__ID__NATURAL16=5
python -m yukon.io
