steps:
  - label: ':nodejs: Run JavaScript checks'
    plugins:
      - docker#v3.5.0:
          image: "node:12"
          workdir: /app
    command:
      - npm install --prefix src/yukon/frontend
      - npm run test --prefix src/yukon/frontend
      - npm run lint --prefix src/yukon/frontend

  - label: ':python: Run Pyhton checks'
    command: tox -p auto -e "{py37,py38}-{test,doctest},pylint,mypy,report"
