steps:
  - label: Upload pipelines
    command:
      - buildkite-agent pipeline upload --replace .buildkite/pipeline.yml
      # - buildkite-agent pipeline upload --replace .buildkite/pipeline.release.yml

  - wait

  - label: ':nodejs: Run JavaScript checks'
    plugins:
      - docker#v3.5.0:
          image: "node:12"
          workdir: /app
    command:
      - npm install --prefix src/yukon/frontend
      - npm run test --prefix src/yukon/frontend
      - npm run lint --prefix src/yukon/frontend

  - label: ':python: Run tests'
    command: tox -p auto -e {py37,py38}-{test,doctest},pylint,mypy,report

  - wait

  - label: "🚀Release"
    trigger: "yukon-release"
    branches: master
    if: build.tag != null
